services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    # tty: true
    environment:
      TZ: Asia/Ho_Chi_Minh
    restart: unless-stopped
    volumes:
      - .:/usr/local/src/app
      - ./stack/php-fpm/php.ini:/usr/local/etc/php/php.ini
    working_dir: /usr/local/src/app
    networks:
      - sennet
  nginx:
    image: nginx
    restart: unless-stopped
    depends_on:
      - php-fpm
    links:
      - php-fpm
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - NGINX_PORT=80
      - FASTCGI_HOST=php-fpm
      - FASTCGI_PORT=9000
    ports:
      - 127.0.0.1:8081:80
    volumes:
      - ./stack/nginx/templates:/etc/nginx/templates
    volumes_from:
      - php-fpm
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      - sennet
networks:
  sennet:
    driver: bridge